# Generated by Django 5.2.8 on 2025-11-25 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
