# Generated by Django 5.2.8 on 2025-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_likes_user_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Dessert", "Dessert"),
                ],
                default="Dinner",
                max_length=50,
            ),
        ),
    ]
