# Generated by Django 5.2.7 on 2025-12-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_category'),
        ('recipes', '0006_recipeimage'),
    ]

    operations = [
    ]
