# Generated by Django 5.2.7 on 2025-12-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment_likes'),
        ('recipes', '0010_user_following'),
    ]

    operations = [
    ]
