# Generated by Django 5.2.7 on 2025-12-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_merge_0005_comment_likes_0010_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Your recipes will only be visible to followers. Other Recipify users will only be able to follow you once you approve their follow request.'),
        ),
    ]
