# Generated by Django 5.2.7 on 2025-12-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_followrequest'),
        ('recipes', '0015_shoppinglistitem'),
    ]

    operations = [
    ]
