# Generated by Django 5.2.7 on 2025-12-14 15:56

import recipes.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_merge_0015_followrequest_0015_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=300, validators=[recipes.models.user.validate_bio_lines]),
        ),
    ]
