# Generated by Django 5.2.7 on 2025-12-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_recipeview"),
        ("recipes", "0016_merge_0015_followrequest_0015_shoppinglistitem"),
    ]

    operations = []
