# Generated by Django 5.2.7 on 2025-12-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_merge_20251212_2157'),
        ('recipes', '0021_alter_notification_content_type_and_more'),
    ]

    operations = [
    ]
