# Generated by Django 5.2.7 on 2025-12-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_merge_20251214_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeView',
        ),
    ]
