# Generated by Django 5.2.7 on 2025-12-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_merge_20251214_2029'),
        ('recipes', '0023_delete_recipeview'),
    ]

    operations = [
    ]
